from typing import overload

class Network:
    @overload
    def __init__(self, dimensions: int): ...

    @overload
    def __init__(self, dimensions: int, num_editors: int, num_articles: int): ...

    def add_editor(self)->None: ...

    def add_article(self)->None: ...

    @property
    def editor_ids(self)->list[int]: ...

    @property
    def article_ids(self)->list[int]: ...

    def create_connections(self)->None: ...

    def clear_connections(self)->None: ...

    @property
    def adjacency(self)->dict[int, int]: ...

    def update_articles(self)->None: ...